import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My PWA Next app",
  description: "Generated by create next app",
  manifest: "/local-manifest.json",
  keywords: ["nextjs", "next14", "pwa", "next-pwa"],
  icons: [
    {rel: "apple-touch-icon", url: "/icon512_maskable.png"},
    {rel: "icon", url: "/icon512_maskable.png"},
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    {children}
    </body>
    </html>
  );
}
